INSERT INTO role (name) SELECT 'ROLE_STUDENT' WHERE NOT EXISTS (SELECT * FROM role WHERE role.name='ROLE_STUDENT');
INSERT INTO role (name) SELECT 'ROLE_TEACHER' WHERE NOT EXISTS (SELECT * FROM role WHERE role.name='ROLE_TEACHER');
INSERT INTO role (name) SELECT 'ROLE_ADMIN' WHERE NOT EXISTS (SELECT * FROM role WHERE role.name='ROLE_ADMIN');

